### ISSUE TITLE
[Experimental] Use SCO OPEN to forcefully open audio without the need for a phonecall

### ISSUE THREAD

**Issue by chris007de** [bt-trx/firmware#30]
The iWrap documentation shows the possibility to forcefully open the SCO connection without the need for the HFP connection, which would yield an audio connection without the need for starting/handling a phone call.

Implement this experimentally, see if it works and if its compatible to any bluetooth device. Let's call it "direct audio" for now

**Comment by dl1com** [comment]
Two users have tested this feature with their cars. Unfortunately, the transceiver sound is not available when the car radio is in radio mode.
Therefore, we'll not develop this further.
