### ISSUE TITLE
Check if iWrap command "PLAYSOUND" can be used to indicate PTT (de)activation

### ISSUE THREAD

**Issue by chris007de** [bt-trx/firmware#32]
Acoording to the iWrap datasheet, we can play sounds using the PLAYSOUND command.
We could indicate PTT on and off by playing a sound, so users without a PTT LED know about the PTT state.

**Comment by phl0** [comment]
It seems that per default the sound is played to the radio interface and not to the connected Bluetooth device.

**Comment by dl1com** [comment]
As seen during implementation of #55, @phl0 is right. PLAYSOUND is played on the radio output, not on the bluetooth device. Therefore not suitable for this use case.
